version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5555:5555"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
